export {default as Navbar} from "./Navbar/Navbar"
export {default as Banner} from "./Banner/Banner"
export {default as About} from "./About/About"
export {default as Footer} from "./Footer/Footer"
export {default as CitiesCard} from "./CitiesCard/CitiesCard"
export {default as Alphabet} from "./Alphabet/Alphabet"
export {default as PlacesCard} from "./PlacesCard/PlacesCard"
export {default as Comments} from "./Comments/Comments"