export {default as Navbar} from "./Navbar/Navbar"
export {default as Banner} from "./Banner/Banner"
export {default as About} from "./About/About"
export {default as Footer} from "./Footer/Footer"
export {default as CitiesCard} from "./CitiesCard/CitiesCard"